version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/Lutron Leap.indigoPlugin/Contents/Server Plugin"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
